load("@my_custom_rules//:ghs_macros.bzl", "make_library")
# load("@my_custom_rules//:convertCcInfo.bzl", "print_ccinfo")
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "CommonConfig",
    hdrs =
        [
            "mcal/imx8-package1/plugins/Base/include/Adc_MemMap.h",
            "mcal/imx8-package1/plugins/Base/include/Compiler.h",
            "mcal/imx8-package1/plugins/Base/include/CompilerDefinition.h",
            "mcal/imx8-package1/plugins/Base/include/Compiler_Cfg.h",
            "mcal/imx8-package1/plugins/Base/include/Dio_MemMap.h",
            "mcal/imx8-package1/plugins/Base/include/Gpt_MemMap.h",
            "mcal/imx8-package1/plugins/Base/include/Icu_MemMap.h",
            "mcal/imx8-package1/plugins/Base/include/Mcal.h",
            "mcal/imx8-package1/plugins/Base/include/Mcl_MemMap.h",
            "mcal/imx8-package1/plugins/Base/include/Mcu_MemMap.h",
            "mcal/imx8-package1/plugins/Base/include/Platform_Types.h",
            "mcal/imx8-package1/plugins/Base/include/Port_MemMap.h",
            "mcal/imx8-package1/plugins/Base/include/Pwm_MemMap.h",
            "mcal/imx8-package1/plugins/Base/include/RegLockMacros.h",
            "mcal/imx8-package1/plugins/Base/include/SilRegMacros.h",
            "mcal/imx8-package1/plugins/Base/include/Soc_Ips.h",
            "mcal/imx8-package1/plugins/Base/include/Spi_MemMap.h",
            "mcal/imx8-package1/plugins/Base/include/StdRegMacros.h",
            "mcal/imx8-package1/plugins/Base/include/Std_Types.h",
            "mcal/imx8-package1/plugins/Base/include/Wdg_MemMap.h",
        ],
    defines = [
        "BRS_COMP_GHS",
        "BRS_CPU_CORE_CORTEX_M4",
        "BRS_DERIVATIVE_IMX8QXP",
        "BRS_OS_USECASE_OS",
        "BRS_PROGRAM_CODE_LOCATION_RAM",
        "BRS_VECTOR_TABLE_LOCATION_RAM",
        "DEBUG_ASSERT_ON",
        "DemoFbl",
        "IOHWAB_TASK_TEST_ENABLE",
        "SEC_KEY_USED=1",
        "VCONST=const",
        "NDEBUG",
        "PROJ_VAR=V710_ED3"
    ],
    includes = ["mcal/imx8-package1/plugins/Base/include"],
)

cc_library(
    name = "ScfwConfig",
    srcs = [
        "mcal/imx8-package1/plugins/Scfw/svc/irq/irq_rpc_clnt.c",
        "mcal/imx8-package1/plugins/Scfw/svc/misc/misc_rpc_clnt.c",
        "mcal/imx8-package1/plugins/Scfw/svc/pad/pad_rpc_clnt.c",
        "mcal/imx8-package1/plugins/Scfw/svc/pm/pm_rpc_clnt.c",
        "mcal/imx8-package1/plugins/Scfw/svc/rm/rm_rpc_clnt.c",
        "mcal/imx8-package1/plugins/Scfw/svc/seco/seco_rpc_clnt.c",
        "mcal/imx8-package1/plugins/Scfw/svc/timer/timer_rpc_clnt.c",
    ],
    hdrs = [
        "mcal/imx8-package1/plugins/Scfw/main/imx8dxl_pads.h",
        "mcal/imx8-package1/plugins/Scfw/main/imx8qm_pads.h",
        "mcal/imx8-package1/plugins/Scfw/main/imx8qx_pads.h",
        "mcal/imx8-package1/plugins/Scfw/main/ipc.h",
        "mcal/imx8-package1/plugins/Scfw/main/rpc.h",
        "mcal/imx8-package1/plugins/Scfw/main/scfw.h",
        "mcal/imx8-package1/plugins/Scfw/main/types.h",
        "mcal/imx8-package1/plugins/Scfw/svc/irq/irq_api.h",
        "mcal/imx8-package1/plugins/Scfw/svc/irq/irq_rpc.h",
        "mcal/imx8-package1/plugins/Scfw/svc/misc/misc_api.h",
        "mcal/imx8-package1/plugins/Scfw/svc/misc/misc_rpc.h",
        "mcal/imx8-package1/plugins/Scfw/svc/pad/pad_api.h",
        "mcal/imx8-package1/plugins/Scfw/svc/pad/pad_rpc.h",
        "mcal/imx8-package1/plugins/Scfw/svc/pm/pm_api.h",
        "mcal/imx8-package1/plugins/Scfw/svc/pm/pm_rpc.h",
        "mcal/imx8-package1/plugins/Scfw/svc/rm/rm_api.h",
        "mcal/imx8-package1/plugins/Scfw/svc/rm/rm_rpc.h",
        "mcal/imx8-package1/plugins/Scfw/svc/seco/seco_api.h",
        "mcal/imx8-package1/plugins/Scfw/svc/seco/seco_rpc.h",
        "mcal/imx8-package1/plugins/Scfw/svc/timer/timer_api.h",
        "mcal/imx8-package1/plugins/Scfw/svc/timer/timer_rpc.h",
    ],
    includes = [
        "mcal/imx8-package1/plugins/Scfw/main",
        "mcal/imx8-package1/plugins/Scfw/svc/irq",
        "mcal/imx8-package1/plugins/Scfw/svc/misc",
        "mcal/imx8-package1/plugins/Scfw/svc/pad",
        "mcal/imx8-package1/plugins/Scfw/svc/pm",
        "mcal/imx8-package1/plugins/Scfw/svc/rm",
        "mcal/imx8-package1/plugins/Scfw/svc/seco",
        "mcal/imx8-package1/plugins/Scfw/svc/timer",
    ],
    deps = [
        ":sec_lib_cc",
        ":CommonConfig",
    ],
)


make_library(
    name = "hero",
    deps=[":CommonConfig",":ScfwConfig"]
)

make_library(
    name = "SpiConfig",
    srcs = [
        "mcal/imx8-package1/plugins/Spi/src/Spi.c",
        "mcal/imx8-package1/plugins/Spi/src/Spi_IPW.c",
        "mcal/imx8-package1/plugins/Spi/src/Spi_LPspi.c",
        "mcal/imx8-package1/plugins/Spi/src/Spi_LPspi_Irq.c",
    ],
    hdrs = [
        "mcal/imx8-package1/plugins/Spi/include/Reg_eSys_LPspi.h",
        "mcal/imx8-package1/plugins/Spi/include/Spi.h",
        "mcal/imx8-package1/plugins/Spi/include/Spi_IPW.h",
        "mcal/imx8-package1/plugins/Spi/include/Spi_IPW_Types.h",
        "mcal/imx8-package1/plugins/Spi/include/Spi_LPspi.h",
    ],
    includes = ["mcal/imx8-package1/plugins/Spi/include"],
    deps = [

        ##########
        ":CommonConfig",
        "@bl-app//:Appl_include",
        "@bl-app//:Appl_Gendata_include",
        # #############
        ":FblBswConfig_new",
        #########
        ":Mcal",
        #########
    ],
)

cc_library(
    name = "Mcal",
    hdrs = ["mcal/include/Os_memmap.h"],
    includes = ["mcal/include"],
)

make_library(
    name = "FblBswConfig_new",
    srcs = [
        # "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/EcuM:include/EcuM.h",
        #"//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/EcuM:src/EcuM.c",
        "mcal/imx8-package1/plugins/EcuM/src/EcuM.c",
        #"//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/EcuM:include/EcuM_Cbk.h",
        #"//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/EcuM:include/EcuM.h",
        "BSW/PduR/PduR_RmIf.c",
        "BSW/PduR/PduR_RmTp.c",
        "BSW/PduR/PduR_RmTp_TxInst.c",
        "BSW/PduR/PduR_Sm.c",
        "BSW/SecMod/Sec.c",
        "BSW/SecMod/Sec_Crc.c",
        "BSW/SecMod/Sec_SeedKey.c",
        "BSW/SecMod/Sec_Verification.c",
        "BSW/vMemAccM/vMemAccM.c",
        "BSW/vMemAccM/vMemAccM_MemAb.c",
        "BSW/vMemAccM/vMemAccM_Proc.c",
        "BSW/VStdLib/vstdlib.c",
        "BSW/gip/extflash.c",
        "BSW/gip/extflash_Acore.c",
        "BSW/gip/fbl_gipfio.c",
        "BSW/Flash/fbl_flio.c",
        "BSW/Flash/FlashRom.c",
        "BSW/PduR/PduR.c",
        "BSW/PduR/PduR_Bm.c",
        "BSW/PduR/PduR_Fm.c",
        "BSW/PduR/PduR_IFQ.c",
        "BSW/PduR/PduR_Lock.c",
        "BSW/PduR/PduR_McQ.c",
        "BSW/CanTp/CanTp.c",
        "BSW/Can/Can.c",
        "BSW/Can/Can_Irq.c",
        "BSW/CanIf/CanIf.c",
        "BSW/Cmpr/cmpr.c",
        "BSW/Det/Det.c",
        "BSW/Eep/EepIO.c",
        "BSW/Fbl/fbl_applvect.c",
        "BSW/Fbl/fbl_diag.c",
        "BSW/Fbl/fbl_fsm.c",
        "BSW/Fbl/fbl_hw.c",
        "BSW/Fbl/fbl_lbt_access.c",
        "BSW/Fbl/fbl_main.c",
        "BSW/Fbl/fbl_mem.c",
        "BSW/Fbl/fbl_nvpattern.c",
        "BSW/Fbl/fbl_ramio.c",
        "BSW/Fbl/fbl_valstruct.c",
        "BSW/Fbl/fbl_wd.c",
        "BSW/FblAsrStubs/Dem.c",
        "BSW/FblBm/bm_shared.c",
        "BSW/FblBmHdr/_Template/_bm_hdr_ap.c",
        "BSW/FblBmHdr/bm_hdr.c",
        "BSW/FblCw/fbl_cw.c",
        "BSW/FblMio/fbl_mem2His.c",
        "BSW/FblMio/fbl_mio.c",
        "BSW/FblSpi_NxpLpspi/_Template/_fbl_spi_nxp_lpspi_cfg.c",
        "BSW/FblSpi_NxpLpspi/fbl_spi_nxp_lpspi.c",
        "BSW/vMemAccM/vMemAccM_Queue.c",
        "BSW/vOtaM/vOtaM.c",
        "BSW/Fbl/fbl_nvpattern_oem.c",
    ],
    hdrs = [
        "BSW/Can/Can.h",
        "BSW/Can/Can_Local.h",
        "BSW/CanIf/CanIf.h",
        "BSW/CanIf/CanIf_Cbk.h",
        "BSW/CanIf/CanIf_GeneralTypes.h",
        "BSW/CanIf/CanIf_Types.h",
        "BSW/CanTp/CanTp.h",
        "BSW/CanTp/CanTp_Cbk.h",
        "BSW/CanTp/CanTp_Priv.h",
        "BSW/CanTp/CanTp_Types.h",
        "BSW/Cmpr/cmpr.h",
        "BSW/Eep/EepIO.h",
        "BSW/Eep/EepInc.h",
        "BSW/Fbl/applvect.h",
        "BSW/Fbl/fbl_assert.h",
        "BSW/Fbl/fbl_assert_oem.h",
        "BSW/Fbl/fbl_def.h",
        "BSW/Fbl/fbl_diag.def",
        "BSW/Fbl/fbl_diag.h",
        "BSW/Fbl/fbl_diag.imp",
        "BSW/Fbl/fbl_fsm.h",
        "BSW/Fbl/fbl_fsm_cfg.h",
        "BSW/Fbl/fbl_fsm_inc.h",
        "BSW/Fbl/fbl_hw.h",
        "BSW/Fbl/fbl_lbt_access.h",
        "BSW/Fbl/fbl_main.h",
        "BSW/Fbl/fbl_main_types.h",
        "BSW/Fbl/fbl_mem.h",
        "BSW/Fbl/fbl_mem_oem.h",
        "BSW/Fbl/fbl_nvpattern.h",
        "BSW/Fbl/fbl_nvpattern_oem.h",
        "BSW/Fbl/fbl_ramio.h",
        "BSW/Fbl/fbl_ramio_inc.h",
        "BSW/Fbl/fbl_sfr.h",
        "BSW/Fbl/fbl_valstruct.h",
        "BSW/Fbl/fbl_valstruct_oem.h",
        "BSW/Fbl/fbl_wd.h",
        "BSW/Fbl/v_ver.h",
        "BSW/FblBm/bm_main.h",
        "BSW/FblBm/bm_shared.h",
        "BSW/FblBm/bm_types.h",
        "BSW/FblBmHdr/bm_hdr.h",
        "BSW/FblBmHdr/bm_hdr_types.h",
        "BSW/FblCw/fbl_cw.h",
        "BSW/FblMio/fbl_mem2His.h",
        "BSW/FblMio/fbl_mio.h",
        "BSW/FblMio/iotypes.h",
        "BSW/FblSpi_NxpLpspi/fbl_spi_nxp_lpspi.h",
        "BSW/FblSpi_NxpLpspi/fbl_spi_nxp_lpspi_inc.h",
        "BSW/FblSpi_VectorIf/fbl_spi_if.h",
        "BSW/Flash/FlashRom.h",
        "BSW/Flash/fbl_flio.h",
        "BSW/Flash/flashdrv.h",
        "BSW/PduR/PduR.h",
        "BSW/PduR/PduR_Bm.h",
        "BSW/PduR/PduR_Fm.h",
        "BSW/PduR/PduR_IFQ.h",
        "BSW/PduR/PduR_Lock.h",
        "BSW/PduR/PduR_McQ.h",
        "BSW/PduR/PduR_RmIf.h",
        "BSW/PduR/PduR_RmTp.h",
        "BSW/PduR/PduR_RmTp_TxInst.h",
        "BSW/PduR/PduR_Sm.h",
        "BSW/SecMod/Sec.h",
        "BSW/SecMod/SecM.h",
        "BSW/SecMod/Sec_Crc.h",
        "BSW/SecMod/Sec_Inc.h",
        "BSW/SecMod/Sec_SeedKey.h",
        "BSW/SecMod/Sec_Types.h",
        "BSW/SecMod/Sec_Verification.h",
        "BSW/SecMod/Sec_Workspace.h",
        "BSW/VStdLib/vstdlib.h",
        "BSW/_Common/Can_GeneralTypes.h",
        "BSW/_Common/ComStack_Types.h",
        "BSW/_Common/Compiler.h",
        "BSW/_Common/Std_Types.h",
        "BSW/_Common/v_def.h",
        "BSW/gip/extflash.h",
        "BSW/gip/extflash_Acore.h",
        "BSW/gip/extflash_cfg.h",
        "BSW/gip/fbl_gipfio.h",
        "BSW/vMemAccM/vMemAccM.h",
        "BSW/vMemAccM/vMemAccM_ErrorNotification.h",
        "BSW/vMemAccM/vMemAccM_MemAb.h",
        "BSW/vMemAccM/vMemAccM_Proc.h",
        "BSW/vMemAccM/vMemAccM_Queue.h",
        "BSW/vMemAccM/vMemAccM_Types.h",
        "BSW/vMemAccM/vMemAccM_vMemApi.h",
        "BSW/vOtaM/vOtaM.h",
        "BSW/vOtaM/vOtaM_Types.h",
    ],
    includes = [
        "BSW/Can",
        "BSW/CanIf",
        "BSW/CanTp",
        "BSW/Cmpr",
        "BSW/Eep",
        "BSW/Fbl",
        "BSW/FblBm",
        "BSW/FblBmHdr",
        "BSW/FblCw",
        "BSW/FblMio",
        "BSW/FblSpi_NxpLpspi",
        "BSW/FblSpi_VectorIf",
        "BSW/Flash",
        "BSW/PduR",
        "BSW/SecMod",
        "BSW/VStdLib",
        "BSW/_Common",
        "BSW/gip",
        "BSW/vMemAccM",
        "BSW/vOtaM",
    ],
    deps = [
        ##############
        "@ucl//:Common",
        "@ucl//:UclDLConfig",
        "@ucl//:UclSysCommonConfig",
        ###########
        ##Working"//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/EcuM:EcuM_files",
        #"//programs/ford/vcar/bl-app:GenMcalFblConfig",
        ###########
        "@bl-app//:Appl_include",
        ##########
        # "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/EcuM:EcuM_files",
        ############
        "@bl-app//:Appl_Gendata",
        ":DetConfig",
        ##########
        #"//cluster-platform/dijkstra/infrastructure/ucl/src/Common",
        #"//cluster-platform/dijkstra/infrastructure/ucl/src/DataLayer:UclDLConfig",
        ################
        ":EcuM_files",
        ":FblAsrStubs",
        #################
        #"//cluster-platform/dijkstra/infrastructure/ucl/src/System/Common:UclSysCommonConfig",
        ################
        ":CommonConfig",
        #############
    ],
)

cc_library(
    name = "DetConfig",
    #  srcs = ["src/EcuM.c"],
    hdrs = ["BSW/Det/Det.h"],
    includes = ["BSW/Det"],
)

cc_library(
    name = "EcuM_files",
    hdrs = glob(["mcal/imx8-package1/plugins/EcuM/include/*.h"]),
    includes = ["mcal/imx8-package1/plugins/EcuM/include"],
)

################################################################
cc_library(
    name = "FblAsrStubs",
    #  srcs = ["src/EcuM.c"],
    hdrs = [
        "BSW/FblAsrStubs/Dem.h",
        "BSW/FblAsrStubs/EcuM_Cbk.h",
        "BSW/FblAsrStubs/EcuM_Generated_Types.h",
        "BSW/FblAsrStubs/MemIf_Types.h",
        "BSW/FblAsrStubs/OsMain.h",
        "BSW/FblAsrStubs/OsScheduleTable.h",
        "BSW/FblAsrStubs/OsScheduleTable_Cfg.h",
        "BSW/FblAsrStubs/Rte.h",
        "BSW/FblAsrStubs/Rte_EcuM_Type.h",
        "BSW/FblAsrStubs/Rte_Type.h",
        "BSW/FblAsrStubs/v_cfg.h",
    ],
    includes = ["BSW/FblAsrStubs"],
)

make_library(
    name = "GptConfig",
    srcs = [
        "mcal/imx8-package1/plugins/Gpt/src/Gpt.c",
        "mcal/imx8-package1/plugins/Gpt/src/Gpt_Ftm.c",
        "mcal/imx8-package1/plugins/Gpt/src/Gpt_Gpt.c",
        "mcal/imx8-package1/plugins/Gpt/src/Gpt_Ipw.c",
        "mcal/imx8-package1/plugins/Gpt/src/Gpt_LPit.c",
        "mcal/imx8-package1/plugins/Gpt/src/Gpt_Tpm.c",
    ],
    hdrs = glob(["mcal/imx8-package1/plugins/Gpt/include/*.h"]),
    includes = ["mcal/imx8-package1/plugins/Gpt/include"],
    deps = [
        #############
        ":FblAsrStubs",
        ":Mcal",
        ":CommonConfig",
        ###########
        ":MclConfig",
        ###########
        "@bl-app//:Appl_Gendata_include",
        "@bl-app//:Appl_include",
        "@bl-app//:Appl_Gendata",
        ########
        ":DetConfig",
    ],
)

cc_library(
    name = "Gpt_headers",
    hdrs = glob(["mcal/imx8-package1/plugins/Gpt/include/*.h"]),
    includes = ["mcal/imx8-package1/plugins/Gpt/include"],
    #visibility = ["//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Mcl:__pkg__"],
)

make_library(
    name = "MclConfig",
    #srcs = glob(["src/*.c"]),
    srcs = [
        "mcal/imx8-package1/plugins/Mcl/src/CDD_Mcl.c",
        "mcal/imx8-package1/plugins/Mcl/src/Ftm_Common.c",
        "mcal/imx8-package1/plugins/Mcl/src/Gpio_Common.c",
        "mcal/imx8-package1/plugins/Mcl/src/Gpt_Common.c",
        "mcal/imx8-package1/plugins/Mcl/src/IrqSteer_Common.c",
        "mcal/imx8-package1/plugins/Mcl/src/LPit_Common.c",
        "mcal/imx8-package1/plugins/Mcl/src/Lpuart_Common.c",
        "mcal/imx8-package1/plugins/Mcl/src/Mcl_Dma.c",
        "mcal/imx8-package1/plugins/Mcl/src/Mcl_Dma_Irq.c",
        "mcal/imx8-package1/plugins/Mcl/src/Mcl_IPW.c",
        "mcal/imx8-package1/plugins/Mcl/src/Mcl_Lmem.c",
        "mcal/imx8-package1/plugins/Mcl/src/Mcl_Mu.c",
        "mcal/imx8-package1/plugins/Mcl/src/Mcl_Scfw_Ipc.c",
        "mcal/imx8-package1/plugins/Mcl/src/Mcl_Scfw_Irq_Rpc.c",
        "mcal/imx8-package1/plugins/Mcl/src/Mcl_Scfw_Misc_Rpc.c",
        "mcal/imx8-package1/plugins/Mcl/src/Mcl_Scfw_Pad_Rpc.c",
        "mcal/imx8-package1/plugins/Mcl/src/Mcl_Scfw_Pm_Rpc.c",
        "mcal/imx8-package1/plugins/Mcl/src/Mcl_Scfw_Rm_Rpc.c",
        "mcal/imx8-package1/plugins/Mcl/src/Mcl_Scfw_Seco_Rpc.c",
        "mcal/imx8-package1/plugins/Mcl/src/Mcl_Scfw_Timer_Rpc.c",
        "mcal/imx8-package1/plugins/Mcl/src/Rgpio_Common.c",
        "mcal/imx8-package1/plugins/Mcl/src/Tpm_Common.c",
    ],
    hdrs = [
        "mcal/imx8-package1/plugins/Mcl/include/CDD_Mcl.h",
        "mcal/imx8-package1/plugins/Mcl/include/Ftm_Common.h",
        "mcal/imx8-package1/plugins/Mcl/include/Ftm_Common_Types.h",
        "mcal/imx8-package1/plugins/Mcl/include/Gpt_Common.h",
        "mcal/imx8-package1/plugins/Mcl/include/Gpt_Common_Types.h",
        "mcal/imx8-package1/plugins/Mcl/include/LPit_Common_Types.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Dma.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Dma_Types.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_EnvCfg.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_IPW.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_IPW_Notif.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_IPW_Types.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Lmem.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Mu.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Notif.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Ipc.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Irq_Apis.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Irq_Rpc.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Misc_Apis.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Misc_Rpc.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Pad_Apis.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Pad_Rpc.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Pm_Apis.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Pm_Rpc.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Rm_Apis.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Rm_Rpc.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Rpc.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Seco_Apis.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Seco_Rpc.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Timer_Apis.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Timer_Rpc.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Scfw_Types.h",
        "mcal/imx8-package1/plugins/Mcl/include/Mcl_Types.h",
        "mcal/imx8-package1/plugins/Mcl/include/Reg_eSys_Dma.h",
        "mcal/imx8-package1/plugins/Mcl/include/Reg_eSys_Ftm.h",
        "mcal/imx8-package1/plugins/Mcl/include/Reg_eSys_Gpio.h",
        "mcal/imx8-package1/plugins/Mcl/include/Reg_eSys_Gpt.h",
        "mcal/imx8-package1/plugins/Mcl/include/Reg_eSys_IrqSteer.h",
        "mcal/imx8-package1/plugins/Mcl/include/Reg_eSys_LPUART.h",
        "mcal/imx8-package1/plugins/Mcl/include/Reg_eSys_LPit.h",
        "mcal/imx8-package1/plugins/Mcl/include/Reg_eSys_Lmem.h",
        "mcal/imx8-package1/plugins/Mcl/include/Reg_eSys_Mu.h",
        "mcal/imx8-package1/plugins/Mcl/include/Reg_eSys_Rgpio.h",
        "mcal/imx8-package1/plugins/Mcl/include/Reg_eSys_Tpm.h",
        "mcal/imx8-package1/plugins/Mcl/include/Tpm_Common.h",
        "mcal/imx8-package1/plugins/Mcl/include/Tpm_Common_Types.h",
    ],
    includes = ["mcal/imx8-package1/plugins/Mcl/include"],
    deps = [
        #     ###########
        "@bl-app//:Appl_Gendata",
        #     #######
        "@bl-app//:Appl_Gendata_include",
        #     ######
        "@bl-app//:Appl_include",
        ####
        ":Mcal",

        #####
        ":FblAsrStubs",
        #     ##############
        ":CommonConfig",
        ##################     added II #######
        #"//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Gpt:Gpt_headers",
        ####################
        ":Gpt_headers",
        ":IcuConfig",
        ":RteConfig",
        ################ added II
        ":AdcConfig",
        ################ added II
        ":PwmConfig",
        ############# added II
        ":ScfwConfig",
        #     #######
        #     ######
        ":FblBswConfig_new",
    ],
)

cc_library(
    name = "IcuConfig",
    #srcs = glob(["src/*.c"]),
    hdrs = [
        "mcal/imx8-package1/plugins/Icu/include/Icu_EnvCfg.h",
        "mcal/imx8-package1/plugins/Icu/include/Icu_Ftm_Irq.h",
        "mcal/imx8-package1/plugins/Icu/include/Icu_Ftm_Types.h",
        "mcal/imx8-package1/plugins/Icu/include/Icu_Gpt_Irq.h",
        "mcal/imx8-package1/plugins/Icu/include/Icu_Gpt_Types.h",
        "mcal/imx8-package1/plugins/Icu/include/Icu_Tpm_Irq.h",
        "mcal/imx8-package1/plugins/Icu/include/Icu_Tpm_Types.h",
    ],
    includes = ["mcal/imx8-package1/plugins/Icu/include"],
)

make_library(
    name = "RteConfig",
    #srcs = glob(["src/*.c"]),
    srcs = [
        "mcal/imx8-package1/plugins/Rte/src/SchM_Adc.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_CDD_Emmc.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_CDD_Esai.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_CDD_I2c.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_CDD_Mcl.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_CDD_Rpmsg.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_CDD_Uart.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Can.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Crypto.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Dio.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_EisCtrl.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Eth.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_EthTrcv.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Eth_43_EQOS.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Fee.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Fls.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Fr.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Gpt.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Icu.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Lin.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Mcu.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Ocu.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Port.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Pwm.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_RamTst.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Spi.c",
        "mcal/imx8-package1/plugins/Rte/src/SchM_Wdg.c",
    ],
    hdrs = glob(["mcal/imx8-package1/plugins/Rte/include/*.h"]),
    includes = ["mcal/imx8-package1/plugins/Rte/include"],
    deps = [
        ":CommonConfig",
        #     "//programs/ford/vcar/bl-app:GenMcalFblConfig",
        "@bl-app//:Appl_include",
    ],
)

make_library(
    name = "DioConfig",
    srcs = [
        "mcal/imx8-package1/plugins/Dio/src/Dio.c",
        "mcal/imx8-package1/plugins/Dio/src/Dio_Gpio.c",
        "mcal/imx8-package1/plugins/Dio/src/Dio_Ipw.c",
        "mcal/imx8-package1/plugins/Dio/src/Dio_Rgpio.c",
    ],
    hdrs = glob(["mcal/imx8-package1/plugins/Dio/include/*.h"]),
    includes = ["mcal/imx8-package1/plugins/Dio/include"],
    #visibility = ["//programs/ford/vcar/bl-app:__pkg__"],
    deps = [
        #"//programs/ford/vcar/bl-app:GenMcalFblConfig",
        ":CommonConfig",
        #	 "//cluster-platform/turing/fbl/oem_ford/BSW:FblBswConfig",
        ":MclConfig",
        #	 "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Scfw:ScfwConfig",
        ":Mcal",
        #	 "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Det:Det",
        #	 "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Rte:RteConfig",
        ":DetConfig",
        "@bl-app//:Appl_Gendata_include",
        "@bl-app//:Appl_Gendata",
        "@bl-app//:Appl_include",
    ],
)

make_library(
    name = "WdgConfig",
    srcs = [
        "mcal/imx8-package1/plugins/Wdg/src/Wdg_43_Instance0.c",
        "mcal/imx8-package1/plugins/Wdg/src/Wdg_43_Instance1.c",
        "mcal/imx8-package1/plugins/Wdg/src/Wdg_43_Instance2.c",
        "mcal/imx8-package1/plugins/Wdg/src/Wdg_Channel.c",
        "mcal/imx8-package1/plugins/Wdg/src/Wdg_IPW.c",
        "mcal/imx8-package1/plugins/Wdg/src/Wdg_Scfw.c",
        "mcal/imx8-package1/plugins/Wdg/src/Wdg_Wdog.c",
        "mcal/imx8-package1/plugins/Wdg/src/Wdg_Wdog_Isr.c",
    ],
    hdrs = glob(["mcal/imx8-package1/plugins/Wdg/include/*.h"]),
    includes = ["mcal/imx8-package1/plugins/Wdg/include"],
    #visibility = ["//programs/ford/vcar/bl-app:__pkg__"],
    deps = [
        #"//programs/ford/vcar/bl-app:GenMcalFblConfig",
        ":CommonConfig",
        "@wdgm//:WdgIf",
        "@bl-app//:Appl_include",
        "@bl-app//:Appl_Gendata_include",
        # "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/WdgIf:WdgIf",
        ":GptConfig",
        ":ScfwConfig",
        ###Working "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Mcl:MclConfig",
        ":FblAsrStubs",
        #	 "//cluster-platform/turing/fbl/oem_ford/BSW:FblBswConfig",
        #	 "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Mcl:MclConfig",
        #	 "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Scfw:ScfwConfig",
        ":Mcal",
        ###
        ":MclConfig",
        #	 "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Det:Det",
        #	 "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Rte:RteConfig"
    ],
)

make_library(
    name = "PortConfig",
    srcs = [
        "mcal/imx8-package1/plugins/Port/src/Port.c",
        "mcal/imx8-package1/plugins/Port/src/Port_Ipw.c",
        "mcal/imx8-package1/plugins/Port/src/Port_SCFW.c",
    ],
    hdrs = glob(["mcal/imx8-package1/plugins/Port/include/*.h"]),
    includes = ["mcal/imx8-package1/plugins/Port/include"],
    #linkopts = ["-G", "-dual_debug"],
    deps = [
        ":Mcal",
        ":CommonConfig",
        "@bl-app//:Appl_include",
        ":FblBswConfig_new",
        "@bl-app//:Appl_Gendata_include",
        # "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Det",
        ":MclConfig",
        ":RteConfig",
        ":ScfwConfig",
        # "//programs/ford/vcar/bl-app:GenMcalFblConfig",
    ],
)

make_library(
    name = "McuConfig",
    srcs = [
        "mcal/imx8-package1/plugins/Mcu/src/Mcu.c",
        "mcal/imx8-package1/plugins/Mcu/src/Mcu_ASMC.c",
        "mcal/imx8-package1/plugins/Mcu/src/Mcu_CortexM.c",
        "mcal/imx8-package1/plugins/Mcu/src/Mcu_IPW.c",
        "mcal/imx8-package1/plugins/Mcu/src/Mcu_Lpcg.c",
        "mcal/imx8-package1/plugins/Mcu/src/Mcu_Scfw.c",
    ],
    hdrs = glob(["mcal/imx8-package1/plugins/Mcu/include/*.h"]),
    includes = ["mcal/imx8-package1/plugins/Mcu/include"],
    deps = [
        #"//programs/ford/vcar/bl-app:GenMcalFblConfig",
        ":CommonConfig",
        #	 "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/WdgIf:WdgIf",
        #	 "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Gpt:GptConfig",
        ":ScfwConfig",
        #	 "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Mcl:MclConfig",
        #	 "//cluster-platform/turing/fbl/oem_ford/BSW:FblBswConfig",
        ":MclConfig",
        #	 "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Scfw:ScfwConfig",
        ":Mcal",
        #	 "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Det:Det",
        #	 "//cluster-platform/turing/fbl/oem_ford/mcal/imx8-package1/plugins/Rte:RteConfig"
        ":DetConfig",
        "@bl-app//:Appl_include",
        "@bl-app//:Appl_Gendata_include",
        "@bl-app//:Appl_Gendata",
    ],
)

cc_library(
    name = "AdcConfig",
    #srcs = glob(["src/*.c"]),
    hdrs = glob(["mcal/imx8-package1/plugins/Adc/include/*.h"]),
    includes = ["mcal/imx8-package1/plugins/Adc/include"],
)

cc_library(
    name = "PwmConfig",
    #srcs = glob(["src/*.c"]),
    hdrs = glob([
        "mcal/imx8-package1/plugins/Pwm/include/*.h",
    ]),
    includes = ["mcal/imx8-package1/plugins/Pwm/include"],
)
######################################################## 
cc_library( 
    name = "GenMcal_headers",
    hdrs = [
        "BSW/Can/Can.h",
        "BSW/CanIf/CanIf_GeneralTypes.h",
        "BSW/CanIf/CanIf_Types.h",
        "BSW/CanTp/CanTp.h",
        "BSW/CanTp/CanTp_Types.h",
        "BSW/Fbl/fbl_assert_oem.h",
        "BSW/Fbl/fbl_def.h",
        "BSW/Fbl/fbl_lbt_access.h",
        "BSW/Fbl/fbl_main_types.h",
        "BSW/Fbl/fbl_mem_oem.h",
        "BSW/Fbl/fbl_nvpattern.h",
        "BSW/Fbl/fbl_ramio_inc.h",
        "BSW/Fbl/fbl_sfr.h",
        "BSW/Fbl/fbl_valstruct.h",
        "BSW/Fbl/fbl_valstruct_oem.h",
        "BSW/Fbl/v_ver.h",
        #"FblAsrStubs/EcuM_Generated_Types.h",
        "BSW/FblBm/bm_main.h",
        "BSW/FblBm/bm_shared.h",
        "BSW/FblBm/bm_types.h",
        "BSW/FblCw/fbl_cw.h",
        "BSW/FblMio/fbl_mem2His.h",
        "BSW/FblMio/fbl_mio.h",
        "BSW/FblMio/iotypes.h",
        "BSW/Flash/fbl_flio.h",
        "BSW/Flash/flashdrv.h",
        "BSW/PduR/PduR.h",
        "BSW/PduR/PduR_RmTp.h",
        "BSW/PduR/PduR_Sm.h",
        "BSW/SecMod/Sec.h",
        "BSW/SecMod/Sec_Crc.h",
        "BSW/SecMod/Sec_Types.h",
        "BSW/SecMod/Sec_Verification.h",
        "BSW/VStdLib/vstdlib.h",
        "BSW/_Common/Can_GeneralTypes.h",
        "BSW/_Common/ComStack_Types.h",
        "BSW/_Common/Compiler.h",
        "BSW/_Common/v_def.h",
        "BSW/gip/fbl_gipfio.h",
        "BSW/vMemAccM/vMemAccM.h",
        "BSW/vMemAccM/vMemAccM_Types.h",
        "BSW/vMemAccM/vMemAccM_vMemApi.h",
        "BSW/vOtaM/vOtaM_Types.h",
    ],
    includes = [
        "BSW/Can",
        "BSW/CanIf",
        "BSW/CanTp",
        "BSW/Cmpr",
        "BSW/Eep",
        "BSW/Fbl",
        "BSW/FblBm",
        "BSW/FblBmHdr",
        "BSW/FblCw",
        "BSW/FblMio",
        "BSW/FblSpi_NxpLpspi",
        "BSW/FblSpi_VectorIf",
        "BSW/Flash",
        "BSW/PduR",
        "BSW/SecMod",
        "BSW/VStdLib",
        "BSW/_Common",
        "BSW/gip",
        "BSW/vMemAccM",
        "BSW/vOtaM",
    ],
    #visibility = ["//programs/ford/vcar/bl-app:__pkg__"],
    deps = [":FblAsrStubs"],
)

make_library(
    name = "sec_lib",
    archives = ["BSW/SecMod/SecMod.a"],
)

cc_library(
    name = "sec_lib_cc",
    srcs = ["BSW/SecMod/SecMod.a"],
)
